#!/usr/bin/env python3
"""Generate the Murphy M4 built-in emergency TrueType subset.

This intentionally does NOT commit a source font. Point it at an OFL/licensed
TrueType file already present in the developer checkout, for example:

  python scripts/gen_m4_emergency_ttf.py \
      --source artifacts/fonts/source/NotoSansCJKsc-Regular.ttf \
      --output src/generated/M4EmergencyTtfData.h

The character set is derived from shipped source/UI strings plus printable
ASCII. Output keeps TrueType quadratic outlines; hint bytecode and all tables
that the firmware parser does not need are removed. The result is a C byte
array so the firmware reads it directly from memory-mapped flash through
TtfEpdFont's MemoryTtfStream without a second font format or RAM copy.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import tempfile
from typing import Iterable, Set

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "src" / "generated" / "M4EmergencyTtfData.h"

# The runtime parser only needs these sfnt tables. `loca` is regenerated by
# fontTools when saving glyf; cmap is subset to BMP format where possible.
REQUIRED_TABLES = {"GlyphOrder", "head", "maxp", "loca", "cmap", "hhea", "hmtx", "glyf"}

# Always make boot/diagnostic/navigation text available even if wording moves
# out of I18n files later. Full reader content still comes from SD/user TTF.
MANDATORY_TEXT = (
    "返回主页目录设置网络文件应用最近阅读加载失败错误字体存储卡触摸电量确定取消"
    "上一页下一页开启关闭刷新系统显示控制"
    "SD ERROR PSRAM FAIL FONT ERROR TOUCH FAIL BACK HOME 0123456789%:/.-_()[]+? "
)

SOURCE_SUFFIXES = {".h", ".hpp", ".c", ".cc", ".cpp", ".ino", ".json"}
SKIP_DIR_NAMES = {
    ".git",
    ".pio",
    "build",
    "artifacts",
    "vendor",
    "node_modules",
    "open-m4-sdk",
    "open-x3-sdk",
    "open-x4-sdk",
}


def iter_source_files(root: pathlib.Path) -> Iterable[pathlib.Path]:
    for path in (root / "src").rglob("*"):
        if not path.is_file() or path.suffix.lower() not in SOURCE_SUFFIXES:
            continue
        if any(part in SKIP_DIR_NAMES for part in path.parts):
            continue
        yield path


def collect_charset(root: pathlib.Path) -> Set[int]:
    chars = {ord(chr(cp)) for cp in range(0x20, 0x7F)}
    chars.update(map(ord, MANDATORY_TEXT))

    # Collect actual non-ASCII source/UI literals. This is deliberately broader
    # than I18n alone: M4 plugin/browser/status strings contain a few direct CJK
    # literals and they should not silently turn into '?'.
    for path in iter_source_files(root):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for ch in text:
            cp = ord(ch)
            # Include non-ASCII printable characters only. Source comments can
            # add glyphs, so strip // and /* */ comments approximately first on
            # a per-file basis below when the file is C/C++-like.
            if cp >= 0x80 and ch.isprintable():
                chars.add(cp)

    # Keep the emergency face BMP-only. The firmware parser supports cmap 12,
    # but all current CJK UI strings fit BMP and format 4 is smaller.
    return {cp for cp in chars if cp <= 0xFFFF}


def strip_comments_for_charset(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def collect_charset_precise(root: pathlib.Path) -> Set[int]:
    chars = {cp for cp in range(0x20, 0x7F)}
    chars.update(map(ord, MANDATORY_TEXT))
    for path in iter_source_files(root):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if path.suffix.lower() in {".h", ".hpp", ".c", ".cc", ".cpp", ".ino"}:
            text = strip_comments_for_charset(text)
        for ch in text:
            cp = ord(ch)
            if 0x80 <= cp <= 0xFFFF and ch.isprintable():
                chars.add(cp)
    return chars


def subset_font(source: pathlib.Path, codepoints: Set[int], out_ttf: pathlib.Path) -> None:
    try:
        from fontTools import subset
        from fontTools.ttLib import TTFont
        from fontTools.ttLib.tables.ttProgram import Program
    except ImportError as exc:
        raise SystemExit(
            "fontTools is required for generation only: python -m pip install fonttools"
        ) from exc

    font = TTFont(str(source), recalcBBoxes=True, recalcTimestamp=False, lazy=False)
    if "glyf" not in font or "loca" not in font:
        raise SystemExit("source must be a plain TrueType glyf/loca font (not CFF/OTF)")
    if "fvar" in font or "gvar" in font:
        raise SystemExit("use a static non-variable TrueType source")

    options = subset.Options()
    options.hinting = False
    options.layout_features = []
    options.name_IDs = []
    options.name_legacy = False
    options.name_languages = []
    options.glyph_names = False
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recommended_glyphs = True
    options.recalc_bounds = True
    options.recalc_timestamp = False
    options.canonical_order = True
    options.prune_unicode_ranges = True
    options.prune_codepage_ranges = True

    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=sorted(codepoints))
    sub.subset(font)

    # Remove per-glyph bytecode explicitly. Quadratic contour points/components
    # are preserved; curves are NOT approximated as lots of straight segments.
    glyf = font["glyf"]
    for glyph_name in font.getGlyphOrder():
        glyph = glyf[glyph_name]
        if hasattr(glyph, "program"):
            glyph.program = Program()

    # Firmware TtfReader intentionally ignores every table outside this set.
    # Drop them before save so flash contains only data that can affect drawing.
    for tag in list(font.keys()):
        if tag not in REQUIRED_TABLES:
            del font[tag]

    # Tiny subsets fit short loca; fontTools may still promote if alignment or
    # size demands it, so this is a preference rather than an invariant.
    if "head" in font:
        font["head"].indexToLocFormat = 0

    font.save(str(out_ttf), reorderTables=True)

    # Reopen once so malformed/minimal table interactions fail during
    # generation rather than on the device.
    check = TTFont(str(out_ttf), lazy=False)
    missing = [tag for tag in ("head", "maxp", "loca", "cmap", "hhea", "hmtx", "glyf") if tag not in check]
    if missing:
        raise SystemExit(f"generated font missing required tables: {missing}")
    if "fvar" in check or "gvar" in check:
        raise SystemExit("generated font unexpectedly remained variable")
    check.close()


def write_header(ttf_path: pathlib.Path, output: pathlib.Path, codepoint_count: int) -> None:
    data = ttf_path.read_bytes()
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "// GENERATED by scripts/gen_m4_emergency_ttf.py. Do not hand edit.",
        "// Plain TrueType glyf subset; read directly from memory-mapped flash.",
        f"// Unicode codepoints requested: {codepoint_count}; bytes: {len(data)}",
        "alignas(4) static const uint8_t kM4EmergencyTtf[] = {",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines += [
        "};",
        "static constexpr size_t kM4EmergencyTtfSize = sizeof(kM4EmergencyTtf);",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=pathlib.Path, help="static TrueType glyf font")
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--charset-out", type=pathlib.Path, default=None,
                        help="optional text file containing the exact generated charset")
    args = parser.parse_args()

    source = args.source.expanduser().resolve()
    if not source.is_file():
        parser.error(f"source font not found: {source}")

    charset = collect_charset_precise(ROOT)
    if args.charset_out:
        chars = "".join(chr(cp) for cp in sorted(charset))
        args.charset_out.parent.mkdir(parents=True, exist_ok=True)
        args.charset_out.write_text(chars, encoding="utf-8")

    with tempfile.TemporaryDirectory(prefix="m4-emergency-ttf-") as td:
        tmp_ttf = pathlib.Path(td) / "subset.ttf"
        subset_font(source, charset, tmp_ttf)
        write_header(tmp_ttf, args.output, len(charset))
        print(f"generated {args.output} ({tmp_ttf.stat().st_size} bytes, {len(charset)} codepoints)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
