#!/usr/bin/env python3
"""Generate GBK-to-Unicode lookup table as a C include file for ESP32 (PROGMEM).

GBK encoding:
  Lead byte:  0x81-0xFE  (126 values)
  Trail byte: 0x40-0x7E, 0x80-0xFE  (190 values, 0x7F is excluded)
  Total slots: 126 * 190 = 23,940

Output: lib/Txt/gbk_table.inc  (uint16_t array initializer)
"""

import os
import sys

LEADS = 126   # 0x81..0xFE
TRAILS = 190  # 0x40..0x7E (63) + 0x80..0xFE (127)


def trail_index(trail: int) -> int:
    if 0x40 <= trail <= 0x7E:
        return trail - 0x40         # 0..62
    if 0x80 <= trail <= 0xFE:
        return trail - 0x80 + 63    # 63..189
    return -1


def main():
    total = LEADS * TRAILS
    table = [0] * total
    mapped = 0

    for lead in range(0x81, 0xFF):
        for trail in list(range(0x40, 0x7F)) + list(range(0x80, 0xFF)):
            try:
                char = bytes([lead, trail]).decode('gbk')
                if len(char) == 1:
                    idx = (lead - 0x81) * TRAILS + trail_index(trail)
                    table[idx] = ord(char)
                    mapped += 1
            except (UnicodeDecodeError, ValueError):
                pass

    # Write the C include file (embedded in firmware flash)
    out_dir = os.path.join(os.path.dirname(__file__), '..', 'lib', 'Txt')
    out_path = os.path.join(out_dir, 'gbk_table.inc')
    cols = 25  # values per line

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by scripts/gen_gbk_table.py — DO NOT EDIT\n')
        f.write(f'// GBK lead 0x81-0xFE ({LEADS}), trail 0x40-0x7E+0x80-0xFE ({TRAILS})\n')
        f.write(f'// {total} slots, {mapped} mapped code points\n')
        for i in range(0, total, cols):
            chunk = table[i:i + cols]
            line = ','.join(f'0x{v:04X}' for v in chunk)
            f.write(line + ',\n')

    print(f'Generated {out_path}')
    print(f'  {total} slots, {mapped} mapped, {total - mapped} zero')
    size_kb = total * 2 / 1024
    print(f'  Table size: {total * 2} bytes ({size_kb:.1f} KB)')


if __name__ == '__main__':
    main()
