#include "GbkToUtf8.h"

// ---------------------------------------------------------------------------
// GBK→Unicode lookup table (23 940 uint16_t entries, ~47 KB).
// Stored in const (DROM) – lives in flash, zero heap usage.
// Generated by: python scripts/gen_gbk_table.py
// ---------------------------------------------------------------------------
static const uint16_t GBK_TABLE[] = {
#include "gbk_table.inc"
};

const uint16_t* getGbkTable() { return GBK_TABLE; }

// ---------------------------------------------------------------------------
// Encoding detection
// ---------------------------------------------------------------------------

bool isValidUtf8(const uint8_t* buf, size_t len) {
  int multiByteCount = 0;
  for (size_t i = 0; i < len; ) {
    const uint8_t b = buf[i];
    if (b < 0x80) { i++; continue; }

    int seqLen = 0;
    if      (b >= 0xC2 && b <= 0xDF) seqLen = 2;
    else if (b >= 0xE0 && b <= 0xEF) seqLen = 3;
    else if (b >= 0xF0 && b <= 0xF4) seqLen = 4;
    else return false;  // Invalid leading byte → not UTF-8

    if (i + static_cast<size_t>(seqLen) > len) break;  // Truncated at boundary → OK
    for (int j = 1; j < seqLen; j++) {
      if ((buf[i + j] & 0xC0) != 0x80) return false;  // Bad continuation → not UTF-8
    }
    multiByteCount++;
    i += static_cast<size_t>(seqLen);
  }
  // Pure ASCII is treated as UTF-8 (no conversion needed).
  return true;
}

// ---------------------------------------------------------------------------
// Conversion helpers
// ---------------------------------------------------------------------------

static inline void appendUtf8(std::string& out, uint16_t cp) {
  if (cp < 0x80) {
    out += static_cast<char>(cp);
  } else if (cp < 0x800) {
    out += static_cast<char>(0xC0 | (cp >> 6));
    out += static_cast<char>(0x80 | (cp & 0x3F));
  } else {
    out += static_cast<char>(0xE0 | (cp >> 12));
    out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
    out += static_cast<char>(0x80 | (cp & 0x3F));
  }
}

// U+FFFD encoded as UTF-8
static constexpr char REPLACEMENT[] = "\xEF\xBF\xBD";

std::string gbkChunkToUtf8(const uint8_t* buf, size_t len,
                           const uint16_t* table,
                           uint8_t& carry, bool& hasCarry) {
  std::string out;
  out.reserve(len + len / 2);  // Chinese 2-byte GBK → 3-byte UTF-8
  size_t i = 0;

  // Handle carry from previous chunk (incomplete GBK double-byte)
  if (hasCarry && len > 0) {
    const uint16_t cp = gbkLookup(table, carry, buf[0]);
    if (cp) appendUtf8(out, cp);
    else    out.append(REPLACEMENT, 3);
    hasCarry = false;
    i = 1;
  }

  while (i < len) {
    const uint8_t b = buf[i];

    // ASCII pass-through (includes \n, \r, \t)
    if (b < 0x80) {
      out += static_cast<char>(b);
      i++;
      continue;
    }

    // GBK double-byte: lead 0x81-0xFE
    if (b >= 0x81 && b <= 0xFE) {
      if (i + 1 >= len) {
        // Incomplete – save for next chunk
        carry = b;
        hasCarry = true;
        break;
      }
      const uint16_t cp = gbkLookup(table, b, buf[i + 1]);
      if (cp) appendUtf8(out, cp);
      else    out.append(REPLACEMENT, 3);
      i += 2;
      continue;
    }

    // Stray byte (0x80 or 0xFF) – skip
    i++;
  }
  return out;
}
