#include "CffReader.h"

#include <algorithm>
#include <cstdint>
#include <vector>

namespace ttf {
namespace {
uint16_t rd16be(const uint8_t* p) { return static_cast<uint16_t>((uint16_t(p[0]) << 8) | p[1]); }
int16_t rds16be(const uint8_t* p) { return static_cast<int16_t>(rd16be(p)); }
uint32_t rd32be(const uint8_t* p) { return (uint32_t(p[0]) << 24) | (uint32_t(p[1]) << 16) | (uint32_t(p[2]) << 8) | p[3]; }
uint32_t tag(const char s[5]) { return (uint32_t(uint8_t(s[0])) << 24) | (uint32_t(uint8_t(s[1])) << 16) | (uint32_t(uint8_t(s[2])) << 8) | uint8_t(s[3]); }
bool decodeDictNumber(const uint8_t* data, size_t len, size_t& pos, int32_t& out) {
  if (pos >= len) return false; const uint8_t b0=data[pos++];
  if (b0>=32&&b0<=246){out=int32_t(b0)-139;return true;}
  if(b0>=247&&b0<=250){if(pos>=len)return false;out=(int32_t(b0)-247)*256+data[pos++]+108;return true;}
  if(b0>=251&&b0<=254){if(pos>=len)return false;out=-(int32_t(b0)-251)*256-data[pos++]-108;return true;}
  if(b0==28){if(len-pos<2)return false;out=rds16be(data+pos);pos+=2;return true;}
  if(b0==29){if(len-pos<4)return false;out=int32_t(rd32be(data+pos));pos+=4;return true;}
  if(b0==30){while(pos<len){uint8_t b=data[pos++];if((b>>4)==15||(b&15)==15){out=0;return true;}}} return false;
}
}

bool CffFont::readAt(uint32_t off, void* dst, uint32_t n) const { return stream_&&off<=fileSize_&&n<=fileSize_-off&&stream_->seek(off)&&stream_->read(dst,n)==n; }
bool CffFont::readOffset(uint32_t off,uint8_t n,uint32_t& v) const {v=0;if(n<1||n>4)return false;uint8_t b[4]={};if(!readAt(off,b,n))return false;for(uint8_t i=0;i<n;i++)v=(v<<8)|b[i];return true;}
bool CffFont::parseIndex(uint32_t rel,IndexInfo& out,uint32_t* next) const {out={};if(!cff_.valid()||rel>cff_.len||cff_.len-rel<2)return false;uint32_t a=cff_.off+rel;uint8_t b[2];if(!readAt(a,b,2))return false;out.count=rd16be(b);out.whole.off=a;if(!out.count){out.whole.len=2;if(next)*next=rel+2;return true;}uint8_t os;if(!readAt(a+2,&os,1)||os<1||os>4)return false;uint64_t ob=uint64_t(out.count+1)*os,dr=uint64_t(rel)+3+ob;if(dr>cff_.len)return false;uint32_t first,last;if(!readOffset(a+3,os,first)||!readOffset(a+3+uint32_t(out.count)*os,os,last)||first!=1||last<first)return false;uint64_t end=dr+last-1;if(end>cff_.len||end>0xffffffffu)return false;out.offSize=os;out.offsetsOff=a+3;out.dataOff=cff_.off+uint32_t(dr);out.whole.len=uint32_t(end-rel);if(next)*next=uint32_t(end);return true;}
bool CffFont::indexObject(const IndexInfo& idx,uint16_t item,Slice& o) const {o={};if(item>=idx.count||!idx.count||!idx.offSize)return false;uint32_t a,b,e=idx.offsetsOff+uint32_t(item)*idx.offSize;if(!readOffset(e,idx.offSize,a)||!readOffset(e+idx.offSize,idx.offSize,b)||!a||b<a)return false;uint64_t off=uint64_t(idx.dataOff)+a-1,len=uint64_t(b)-a,end=uint64_t(idx.whole.off)+idx.whole.len;if(off+len>end||off>0xffffffffu||len>0xffffffffu)return false;o={uint32_t(off),uint32_t(len)};return true;}
bool CffFont::indexObject(Slice idx,uint16_t item,Slice& o) const {if(!idx.valid()||idx.off<cff_.off||idx.off-cff_.off>=cff_.len)return false;IndexInfo p;if(!parseIndex(idx.off-cff_.off,p)||p.whole.len!=idx.len)return false;return indexObject(p,item,o);}

bool CffFont::parseTopDict(Slice dict){if(!dict.valid()||dict.len>65536){lastError_="CFF Top DICT invalid or too large";return false;}std::vector<uint8_t>b(dict.len);if(!readAt(dict.off,b.data(),dict.len))return false;std::vector<int32_t>s;uint32_t cs=0,ps=0,po=0;bool have=false;size_t p=0;while(p<b.size()){uint8_t x=b[p];if(x>=28){int32_t v;if(!decodeDictNumber(b.data(),b.size(),p,v)||s.size()>=48)return false;s.push_back(v);continue;}++p;uint16_t op=x;if(x==12){if(p>=b.size())return false;op=0x0c00|b[p++];}if(op==17){if(s.size()!=1||s[0]<0)return false;cs=uint32_t(s[0]);have=true;}else if(op==18){if(s.size()!=2||s[0]<0||s[1]<0)return false;ps=uint32_t(s[0]);po=uint32_t(s[1]);}s.clear();}if(!have||cs>=cff_.len){lastError_="CFF Top DICT missing CharStrings";return false;}if(ps){if(po>cff_.len||ps>cff_.len-po)return false;privateDict_={cff_.off+po,ps};}if(!parseIndex(cs,charStringsInfo_)||!charStringsInfo_.count)return false;charStrings_=charStringsInfo_.whole;glyphCount_=charStringsInfo_.count;return true;}

bool CffFont::initSfntMetrics(uint32_t face,uint16_t nt){head_=cmap_=hhea_=hmtx_=maxp_={};for(uint16_t i=0;i<nt;i++){uint8_t r[16];if(!readAt(face+12+uint32_t(i)*16,r,16))return false;Table t{rd32be(r+8),rd32be(r+12),true};if(t.off>fileSize_||t.len>fileSize_-t.off)return false;uint32_t k=rd32be(r);if(k==tag("head"))head_=t;else if(k==tag("cmap"))cmap_=t;else if(k==tag("hhea"))hhea_=t;else if(k==tag("hmtx"))hmtx_=t;else if(k==tag("maxp"))maxp_=t;}if(!head_.present||!cmap_.present||!hhea_.present||!hmtx_.present||!maxp_.present){lastError_="CFF OpenType missing head/cmap/hhea/hmtx/maxp";return false;}uint8_t h[54],hh[36],m[6];if(head_.len<54||hhea_.len<36||maxp_.len<6||!readAt(head_.off,h,54)||!readAt(hhea_.off,hh,36)||!readAt(maxp_.off,m,6))return false;unitsPerEm_=rd16be(h+18);bboxYMax_=rds16be(h+42);ascender_=rds16be(hh+4);descender_=rds16be(hh+6);lineGap_=rds16be(hh+8);numHMetrics_=rd16be(hh+34);uint16_t ng=rd16be(m+4);if(!unitsPerEm_||unitsPerEm_>16384||!numHMetrics_||ng!=glyphCount_){lastError_="CFF OpenType metrics inconsistent with CharStrings";return false;}return initCmap();}

bool CffFont::initCmap(){if(cmap_.len<4)return false;uint8_t h[4];if(!readAt(cmap_.off,h,4))return false;uint16_t n=rd16be(h+2);if(!n||n>256||cmap_.len<4+uint32_t(n)*8)return false;std::vector<uint8_t>d(uint32_t(n)*8);if(!readAt(cmap_.off+4,d.data(),d.size()))return false;uint32_t best=0;int score=-1;for(uint16_t i=0;i<n;i++){auto e=d.data()+i*8;uint32_t o=rd32be(e+4);if(o+2>cmap_.len)continue;uint8_t f[2];if(!readAt(cmap_.off+o,f,2))continue;uint16_t fmt=rd16be(f);if(fmt!=4&&fmt!=12)continue;int s=(fmt==12?100:0)+(rd16be(e)==3?(rd16be(e+2)==10?40:30):rd16be(e)==0?20:0);if(s>score){score=s;best=o;}}if(score<0)return false;uint32_t avail=cmap_.len-best;if(avail>2*1024*1024)return false;cmapData_.resize(avail);if(!readAt(cmap_.off+best,cmapData_.data(),avail))return false;uint16_t fmt=rd16be(cmapData_.data());if(fmt==4){if(avail<14)return false;cmapIs12_=false;cmapGroups_=rd16be(cmapData_.data()+6)/2;if(!cmapGroups_||avail<16+cmapGroups_*8)return false;}else{if(avail<16)return false;cmapIs12_=true;cmapGroups_=rd32be(cmapData_.data()+12);if(avail<16+uint64_t(cmapGroups_)*12)return false;}return true;}

bool CffFont::findGlyph(uint32_t cp,uint16_t& gid) const {gid=0;if(!ready_||cmapData_.empty())return false;const uint8_t*p=cmapData_.data();if(!cmapIs12_){if(cp>0xffff)return true;uint32_t ss=cmapGroups_*2;const uint8_t*end=p+14,*start=end+ss+2,*delta=start+ss,*range=delta+ss;uint32_t lo=0,hi=cmapGroups_;while(lo<hi){uint32_t m=(lo+hi)/2;if(cp>rd16be(end+m*2))lo=m+1;else hi=m;}if(lo>=cmapGroups_||cp<rd16be(start+lo*2))return true;int16_t de=rds16be(delta+lo*2);uint16_t ro=rd16be(range+lo*2);if(!ro){gid=uint16_t((int32_t(cp)+de)&0xffff);return true;}uint32_t off=uint32_t(range-p)+lo*2+ro+(cp-rd16be(start+lo*2))*2;if(off+2>cmapData_.size())return true;gid=rd16be(p+off);if(gid)gid=uint16_t(gid+de);return true;}const uint8_t*g=p+16;uint32_t lo=0,hi=cmapGroups_;while(lo<hi){uint32_t m=(lo+hi)/2;const uint8_t*x=g+m*12;if(cp>rd32be(x+4))lo=m+1;else hi=m;}if(lo>=cmapGroups_)return true;const uint8_t*x=g+lo*12;uint32_t st=rd32be(x);if(cp<st)return true;uint32_t id=rd32be(x+8)+(cp-st);if(id<glyphCount_)gid=uint16_t(id);return true;}
bool CffFont::glyphHMetrics(uint16_t gid,int32_t& adv,int32_t& lsb) const {adv=lsb=0;if(!ready_||gid>=glyphCount_||!numHMetrics_)return false;uint8_t b[4];if(gid<numHMetrics_){if(!readAt(hmtx_.off+uint32_t(gid)*4,b,4))return false;adv=rd16be(b);lsb=rds16be(b+2);return true;}if(!readAt(hmtx_.off+uint32_t(numHMetrics_-1)*4,b,2))return false;adv=rd16be(b);uint32_t o=hmtx_.off+uint32_t(numHMetrics_)*4+uint32_t(gid-numHMetrics_)*2;if(!readAt(o,b,2))return false;lsb=rds16be(b);return true;}
void CffFont::fontVMetrics(int32_t&a,int32_t&d,int32_t&g) const {a=ascender_;d=descender_;g=lineGap_;}

bool CffFont::init(TtfStream& stream,uint32_t face){ready_=false;lastError_="not initialized";stream_=&stream;fileSize_=stream.size();cff_={};charStringsInfo_=globalSubrsInfo_=localSubrsInfo_={};charStrings_=globalSubrs_=localSubrs_=privateDict_={};glyphCount_=unitsPerEm_=numHMetrics_=0;cmapData_.clear();if(face>fileSize_||fileSize_-face<12)return false;uint8_t h[12];if(!readAt(face,h,12)||rd32be(h)!=0x4f54544f){lastError_="not an OTTO OpenType face";return false;}uint16_t nt=rd16be(h+4);if(!nt||nt>128||uint64_t(face)+12+uint64_t(nt)*16>fileSize_)return false;bool c2=false;for(uint16_t i=0;i<nt;i++){uint8_t r[16];if(!readAt(face+12+uint32_t(i)*16,r,16))return false;uint32_t k=rd32be(r),o=rd32be(r+8),l=rd32be(r+12);if(k==tag("CFF2"))c2=true;if(k==tag("CFF ")){if(o>fileSize_||l>fileSize_-o||l<4)return false;cff_={o,l};}}if(!cff_.valid()){lastError_=c2?"CFF2 face is not supported yet":"OTTO face has no CFF table";return false;}uint8_t ch[4];if(!readAt(cff_.off,ch,4)||ch[0]!=1||ch[2]<4||ch[2]>cff_.len||ch[3]<1||ch[3]>4)return false;uint32_t rel=ch[2];IndexInfo names,top,strings;if(!parseIndex(rel,names,&rel)||!names.count||!parseIndex(rel,top,&rel)||top.count!=1||!parseIndex(rel,strings,&rel)||!parseIndex(rel,globalSubrsInfo_))return false;globalSubrs_=globalSubrsInfo_.whole;Slice td;if(!indexObject(top,0,td)||!parseTopDict(td)||!parsePrivateDict()||!initSfntMetrics(face,nt))return false;ready_=true;lastError_="ok";return true;}
} // namespace ttf
