#pragma once
// Generated by firmware/scripts/generate_m4_center_kernel.py — do not edit.
// Source TTF is an external input; regenerate with --font <path-to-标准像素粗.ttf>.
// Single system face: CJK center-kernel occupancy plus Latin/punct 16x16 occupancy.

#include <cstddef>
#include <cstdint>

namespace M4CenterKernelFont {

constexpr const char kMagic[4] = {'M', '4', 'C', 'K'};
constexpr uint16_t kVersion = 1;
constexpr uint16_t kGlyphCount = 28985;
constexpr uint8_t kGridWidth = 16;
constexpr uint8_t kGridHeight = 16;
constexpr uint8_t kBitmapBytes = 32;
constexpr uint16_t kHeaderBytes = 48;
constexpr uint16_t kLeafBytes = 34;
constexpr size_t kBlobBytes = 939815;
constexpr int kSourcePx = 16;

constexpr const char* kFontSha256 = "9507b4d3e915455afadfa688e8ea515abf816bce06f76346ee356f0f38810574";
constexpr const char* kSupportedCorpusSha256 = "18387ebc26f884ed492be5f95336df6eb4bd8bdd659ddc707d2478adbc169a9c";
constexpr const char* kBlobSha256 = "ce583aa20d016a5a816464c297d31b3896d56d77c5d9ad59cbb8abb8f2c37586";

}  // namespace M4CenterKernelFont
