#pragma once
// Generated by firmware/scripts/generate_m4_center_kernel.py — do not edit.
// Source TTF is an external input; regenerate with --font <path-to-标准像素粗.ttf>.
// Reader-body CJK occupancy only. Chrome still uses m4_native_grid_15x16.bin.

#include <cstddef>
#include <cstdint>

namespace M4CenterKernelFont {

constexpr const char kMagic[4] = {'M', '4', 'C', 'K'};
constexpr uint16_t kVersion = 1;
constexpr uint16_t kGlyphCount = 27553;
constexpr uint8_t kGridWidth = 16;
constexpr uint8_t kGridHeight = 16;
constexpr uint8_t kBitmapBytes = 32;
constexpr uint16_t kHeaderBytes = 48;
constexpr uint16_t kLeafBytes = 34;
constexpr size_t kBlobBytes = 892817;
constexpr int kSourcePx = 16;

constexpr const char* kFontSha256 = "9507b4d3e915455afadfa688e8ea515abf816bce06f76346ee356f0f38810574";
constexpr const char* kSupportedCorpusSha256 = "6b2fbc2ed86d644787099dc9d23856bb59e7190683ca42d56d7e515fee729844";
constexpr const char* kBlobSha256 = "676f1e0c87fe3caee1ac83d235bbb96f22df6d13ee291633c83c582c58c9d835";

}  // namespace M4CenterKernelFont
