#pragma once
// Generated by firmware/scripts/generate_m4_native_grid.py — do not edit.
// Source TTF is an external input; regenerate with --font <path-to-标准像素粗.ttf>.

#include <cstddef>
#include <cstdint>

namespace M4NativeGridFont {

constexpr const char kMagic[4] = {'M', '4', 'N', 'G'};
constexpr uint16_t kVersion = 1;
constexpr uint16_t kGlyphCount = 28953;
constexpr uint16_t kOutlierCount = 32;
constexpr uint16_t kOccupiedPages = 132;
constexpr uint8_t kGridWidth = 15;
constexpr uint8_t kGridHeight = 16;
constexpr uint8_t kBitmapBytes = 30;
constexpr uint8_t kOutlierBitmapBytes = 32;
constexpr uint16_t kHeaderBytes = 48;
constexpr uint16_t kLeafBytes = 34;
constexpr size_t kBlobBytes = 874726;
constexpr int kSourcePx = 16;

constexpr const char* kFontSha256 = "9507b4d3e915455afadfa688e8ea515abf816bce06f76346ee356f0f38810574";
constexpr const char* kSupportedCorpusSha256 = "f953cc612ae2fc412bda55b4aae8a105b8d6eb105ae3c06269b84c976c2cc1b3";
constexpr const char* kBlobSha256 = "924b4bbd5f45d0208d17477c701df7d459a1966452f98989177358b3788a9960";

}  // namespace M4NativeGridFont
